Add build failure for scancode too

diff --git a/.github/workflows/lab05-license-check.yml b/.github/workflows/lab05-license-check.yml
--- a/.github/workflows/lab05-license-check.yml
+++ b/.github/workflows/lab05-license-check.yml
@@ -90,3 +90,12 @@ jobs:
         with:
           name: Scancode report
           path: ${{github.workspace}}/reports
+      - name: Check licenses found with scancode
+        run: |
+          $unwantedLicenses = ./scripts/scancodeaudit.ps1 ./reports/output.json | Where-Object { $_ -ne "MIT" }
+          if ($unwantedLicenses -gt 0) {
+            # Set proper error message
+            echo "::error file=scripts/scancodeaudit.ps1,title=Unwanted licenses detected::Unwanted licenses detected: $unwantedLicenses"
+            # Error message does not fail the job, use exit 1 to actually make it fail
+            exit 1
+          }
